# GitLab CI/CD Pipeline for DMN Plugin - Single Job
variables:
  MYSQL_ROOT_PASSWORD: root

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

# Single comprehensive test job
test-all:
  stage: test
  image: php:8.1-cli
  before_script:
    - apt-get update -qq && apt-get install -y -qq git unzip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --prefer-dist --no-progress --no-interaction
  script:
    - echo "✅ Running PHPUnit tests..."
    - composer run test:ci
    - echo "✅ Running security scan..."
    - composer run security
    - echo "✅ Running code quality check..."
    - composer run lint:summary || echo "Code quality advisory completed"
    - echo "✅ All checks completed successfully!"
  artifacts:
    reports:
      junit: junit.xml
    expire_in: 1 week
